<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sf_seolighthouse"
 *
 * Auto generated by Extension Builder 2021-03-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Dalle Image Generator',
    'description' => 'Shows text prompt for generating images with dalle ai in realtime',
    'category' => 'misc',
    'author' => 'Andreas Kauhold',
    'author_email' => 'info@stackfactory.de',
    'state' => 'beta',
    'clearCacheOnLoad' => 0,
    'version' => '1.2.0',
    'constraints' => [
        'depends' => [
            'typo3' => '12.0.0-12.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
