<?php

use TYPO3\CMS\Core\Utility\ExtensionManagementUtility;

defined('TYPO3_MODE') or die();

$lll = 'LLL:EXT:sf_dalleimages/Resources/Private/Language/locallang_db.xlf:';

$dalleImage = [
    'tx_dalleimage_prompt_description' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.description',
        'exclude' => 1,
        'config' => [
            'type' => 'input',
            'renderType' => 'sendToDalleButton',
            'size' => 80,
            'max' => 500,
            'eval' => 'trim',
        ],
    ],
    
    'tx_dalleimage_prompt_colors' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.colors',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectMultipleSideBySide',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.colors.black', 'black'],
                [$lll . 'tt_content.dalleimage.prompt.colors.white', 'white'],
                [$lll . 'tt_content.dalleimage.prompt.colors.red', 'red'],
                [$lll . 'tt_content.dalleimage.prompt.colors.blue', 'blue'],
                [$lll . 'tt_content.dalleimage.prompt.colors.green', 'green'],
                [$lll . 'tt_content.dalleimage.prompt.colors.yellow', 'yellow'],
                [$lll . 'tt_content.dalleimage.prompt.colors.orange', 'orange'],
                [$lll . 'tt_content.dalleimage.prompt.colors.purple', 'purple'],
                [$lll . 'tt_content.dalleimage.prompt.colors.pink', 'pink'],
                [$lll . 'tt_content.dalleimage.prompt.colors.brown', 'brown'],
                [$lll . 'tt_content.dalleimage.prompt.colors.grey', 'grey'],
                [$lll . 'tt_content.dalleimage.prompt.colors.cyan', 'cyan'],
                [$lll . 'tt_content.dalleimage.prompt.colors.magenta', 'magenta'],
                [$lll . 'tt_content.dalleimage.prompt.colors.teal', 'teal'],
                [$lll . 'tt_content.dalleimage.prompt.colors.lime', 'lime'],
                [$lll . 'tt_content.dalleimage.prompt.colors.maroon', 'maroon'],
                [$lll . 'tt_content.dalleimage.prompt.colors.olive', 'olive'],
                [$lll . 'tt_content.dalleimage.prompt.colors.navy', 'navy'],
                [$lll . 'tt_content.dalleimage.prompt.colors.aqua', 'aqua'],
            ],
            'size' => 2,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_subject' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.subject',
        'exclude' => 1,
        'config' => [
            'type' => 'input',
            'size' => 10,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_illustration' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.illustration',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.empty', ''],
                [$lll . 'tt_content.dalleimage.prompt.illustration.crayondrawing', 'crayon drawing'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.coloringbook', 'coloring book'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.papercollage', 'paper collage'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.pencilsketch', 'pencil sketch'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.ballpensketch', 'ballpen sketch'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.airbrush', 'airbrush'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.watercolor', 'watercolor'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.acryloncanvas', 'acrylic on canvas'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.oilpainting', 'oil painting'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.oilpastel', 'oil pastel'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.charcoaldrawing', 'charcoal drawing'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.tattoodesign', 'tattoo design'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.graffiti', 'graffiti'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.blueprint', 'blueprint'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.waxcrayon', 'wax crayon'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.coloredink', 'colored ink'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.penandink', 'pen and ink'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.mythologicalmap', 'mythological map'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.botanyillustration', 'botany illustration'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.historicalarchive', 'historical archive'],
                [$lll . 'tt_content.dalleimage.prompt.illustration.medievalmanuscript', 'medieval manuscript'],
              ],              
        ],
    ],
    'tx_dalleimage_prompt_style' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.style',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.empty', ''],
                [$lll . 'tt_content.dalleimage.prompt.style.goth', 'goth'],
                [$lll . 'tt_content.dalleimage.prompt.style.vaporwave', 'vaporwave'],
                [$lll . 'tt_content.dalleimage.prompt.style.postapocalyptic', 'postapocalyptic'],
                [$lll . 'tt_content.dalleimage.prompt.style.cybernetic', 'cybernetic'],
                [$lll . 'tt_content.dalleimage.prompt.style.steampunk', 'steampunk'],
                [$lll . 'tt_content.dalleimage.prompt.style.memphis', 'memphis'],
                [$lll . 'tt_content.dalleimage.prompt.style.dieselpunk', 'dieselpunk'],
                [$lll . 'tt_content.dalleimage.prompt.style.afrofuturism', 'afrofuturism'],
                [$lll . 'tt_content.dalleimage.prompt.style.cyberpunk', 'cyberpunk'],
                [$lll . 'tt_content.dalleimage.prompt.style.biopunk', 'biopunk'],
                [$lll . 'tt_content.dalleimage.prompt.style.vintage', 'vintage'],
                [$lll . 'tt_content.dalleimage.prompt.style.darkacademia', 'dark academia'],
                [$lll . 'tt_content.dalleimage.prompt.style.junglecore', 'junglecore'],
                [$lll . 'tt_content.dalleimage.prompt.style.childrensdrawing', 'childrens drawing'],
                [$lll . 'tt_content.dalleimage.prompt.style.popart', 'pop art'],
                [$lll . 'tt_content.dalleimage.prompt.style.princesscore', 'princesscore'],
                [$lll . 'tt_content.dalleimage.prompt.style.psychedelica', 'psychedelica'],
                [$lll . 'tt_content.dalleimage.prompt.style.rococo', 'rococo'],
                [$lll . 'tt_content.dalleimage.prompt.style.tanbikei', 'tanbi kei'],
                [$lll . 'tt_content.dalleimage.prompt.style.teslapunk', 'teslapunk'],
                [$lll . 'tt_content.dalleimage.prompt.style.ukiyoe', 'ukiyo-e'],
                [$lll . 'tt_content.dalleimage.prompt.style.wabisabi', 'wabi-sabi'],
                [$lll . 'tt_content.dalleimage.prompt.style.xrayimage', 'x-ray image'],
                [$lll . 'tt_content.dalleimage.prompt.style.infrared', 'infrared'],
                [$lll . 'tt_content.dalleimage.prompt.style.ultraviolet', 'ultraviolet'],
                [$lll . 'tt_content.dalleimage.prompt.style.thermalphoto', 'thermal photo'],
                [$lll . 'tt_content.dalleimage.prompt.style.1950ssuburbia', '1950s suburbia'],
                [$lll . 'tt_content.dalleimage.prompt.style.2tone', '2 tone'],
                [$lll . 'tt_content.dalleimage.prompt.style.2000sautumn', '2000s autumn'],
                [$lll . 'tt_content.dalleimage.prompt.style.2014eratumblr', '2014 era tumblr'],
                [$lll . 'tt_content.dalleimage.prompt.style.2kanimecore', '2k animecore'],
                [$lll . 'tt_content.dalleimage.prompt.style.70sdisco', '70s disco'],
                [$lll . 'tt_content.dalleimage.prompt.style.uhd8k', 'uhd 8k'],
            ],                 
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_artworks' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.artworks',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.empty', ''],
                [$lll . 'tt_content.dalleimage.prompt.artworks.scoobydoo', 'scooby doo'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.flintstones', 'flintstones'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.familyguy', 'family guy'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.thesimpsons', 'the simpsons'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.looneytunes', 'looney tunes'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.bojackhorseman', 'bojack horseman'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.drseuss', 'dr seuss'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.themuppetshow', 'the muppet show'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.themoviematrix', 'the movie matrix'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.studioghibli', 'studio ghibli'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.disney2d', 'disney 2d'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.disney3d', 'disney 3d'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.pixar', 'pixar'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.sincity', 'sin city'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.spidermanauniverse', 'spiderman universe'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.archer', 'archer'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.futurama', 'futurama'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.southpark', 'south park'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.adventuretime', 'adventure time'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.akira', 'akira'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.cowboybebop', 'cowboy bebop'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.gorillaz', 'gorillaz'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.thelegendofkorra', 'the legend of korra'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.sailormoon', 'sailor moon'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.onepiece', 'one piece'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.ghostintheshell', 'ghost in the shell'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.renandstimpy', 'ren and stimpy'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.beavisandbutthead', 'beavis and butthead'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.kingofthehill', 'king of the hill'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.popeye', 'popeye'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.batmananimatedseries', 'batman animated series'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.powerpuffgirls', 'powerpuff girls'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.teenagemutantninjaturtles', 'teenage mutant ninja turtles'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.xmenanimatedseries', 'x-men animated series'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.myneighbor_totoro', 'my neighbor totoro'],
            ],
            'max' => 255,
            'eval' => 'trim',
        ],
    ],

    'tx_dalleimage_prompt_artists' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.artists',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.empty', ''],
                [$lll . 'tt_content.dalleimage.prompt.artists.salvadordali', 'salvador dali'],
                [$lll . 'tt_content.dalleimage.prompt.artists.fridakahlo', 'frida kahlo'],
                [$lll . 'tt_content.dalleimage.prompt.artists.banksy', 'banksy'],
                [$lll . 'tt_content.dalleimage.prompt.artists.picasso', 'picasso'],
                [$lll . 'tt_content.dalleimage.prompt.artists.davinci', 'da vinci'],
                [$lll . 'tt_content.dalleimage.prompt.artists.michelangelo', 'michelangelo'],
                [$lll . 'tt_content.dalleimage.prompt.artists.vangogh', 'van gogh'],
                [$lll . 'tt_content.dalleimage.prompt.artists.monet', 'monet'],
                [$lll . 'tt_content.dalleimage.prompt.artists.timburton', 'tim burton'],
                [$lll . 'tt_content.dalleimage.prompt.artists.takashimurakami', 'takashi murakami'],
                [$lll . 'tt_content.dalleimage.prompt.artists.franciscodegoya', 'francisco de goya'],
                [$lll . 'tt_content.dalleimage.prompt.artists.jeffkoons', 'jeff koons'],
                [$lll . 'tt_content.dalleimage.prompt.artists.andywarhol', 'andy warhol'],
                [$lll . 'tt_content.dalleimage.prompt.artists.frankmiller', 'frank miller'],
                [$lll . 'tt_content.dalleimage.prompt.artists.marjanesatrapi', 'marjane satrapi'],
                [$lll . 'tt_content.dalleimage.prompt.artists.keithharing', 'keith haring'],
                [$lll . 'tt_content.dalleimage.prompt.artists.edwardhopper', 'edward hopper'],
                [$lll . 'tt_content.dalleimage.prompt.artists.lisafrank', 'lisa frank'],
                [$lll . 'tt_content.dalleimage.prompt.artists.robertcrumb', 'robert crumb'],
                [$lll . 'tt_content.dalleimage.prompt.artists.roylichenstein', 'roy lichtenstein'],
                [$lll . 'tt_content.dalleimage.prompt.artists.arthurrachkam', 'arthur rackham'],
                [$lll . 'tt_content.dalleimage.prompt.artists.zahahadid', 'zaha hadid'],
                [$lll . 'tt_content.dalleimage.prompt.artists.shraza', 'sh razza'],
                [$lll . 'tt_content.dalleimage.prompt.artists.dorothealange', 'dorothea lange'],
                [$lll . 'tt_content.dalleimage.prompt.artists.cindysherman', 'cindy sherman'],
                [$lll . 'tt_content.dalleimage.prompt.artists.liuxiaodong', 'liu xiaodong'],
                [$lll . 'tt_content.dalleimage.prompt.artists.terryrichardson', 'terry richardson'],
                [$lll . 'tt_content.dalleimage.prompt.artists.georgehurrell', 'george hurrell'],
                [$lll . 'tt_content.dalleimage.prompt.artists.junjiito', 'junji ito'],
                [$lll . 'tt_content.dalleimage.prompt.artists.billwatterson', 'bill watterson'],
            ],              
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_lighting' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.lighting',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.empty', ''],
                [$lll . 'tt_content.dalleimage.prompt.lighting.goldenhour', 'golden hour'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.bluehour', 'blue hour'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.midday', 'midday'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.overcast', 'overcast'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.warm', 'warm'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.cold', 'cold'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.flashphotography', 'flash photography'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.colorfullightning', 'colorful lightning'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.reallightsource', 'real light source'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.highkeylighting', 'high key lighting'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.backlighting', 'backlighting'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.studiolighting', 'studio lighting'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.studioportrait', 'studio portrait'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.litfromabove', 'lit from above'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.litfrombelow', 'lit from below'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.sidelighting', 'side lighting'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.softlighting', 'soft lighting'],
            ],              
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_film_type' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.filmtype',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.empty', ''],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.cyanotype', 'cyanotype'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.blackandwhite', 'black and white'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.redscale', 'redscale'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.infrared', 'infrared'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.bleachbypass', 'bleach bypass'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.instagramhipstamatic2015', 'instagram hipstamatic 2015'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.contactsheet', 'contact sheet'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.coloursplash', 'colour splash'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.solarised', 'solarised'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.anaglyph', 'anaglyph'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.polaroid600filmcolor', 'polaroid 600 film color'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.kodakinfraredfilm', 'kodak infrared film'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.kodakxrayfilm', 'kodak x-ray film'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.kodakkodachromefilm', 'kodak kodachrome film'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.kodachrome64', 'kodachrome 64'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.kodakektar100', 'kodak ektar 100'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.fujisuperia200', 'fuji superia 200'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.fujipro400h', 'fuji pro 400h'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.fujichromevelvia100', 'fuji chrome velvia 100'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.ilfordhp5', 'ilford hp5'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.ilforddelta3200', 'ilford delta 3200'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.konicaminoltapro200s', 'konica minolta pro 200s'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.anscochrome200', 'anscochrome 200'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.ektachrome100', 'ektachrome 100'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.lomochromepurple100400', 'lomochrome purple 100-400'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.lomochrometurquoise100400', 'lomochrome turquoise 100-400'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.lomographyxpro200', 'lomography x-pro 200'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.heliochrome', 'heliochrome'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.polaroid600film', 'polaroid 600 film'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.revologstreak', 'revolog streak'],
            ],              
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_camera_position' => [
        'exclude' => true,
        'label' => $lll . 'tt_content.dalleimage.prompt.camera_position',
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.empty', ''],
                [$lll . 'tt_content.dalleimage.prompt.camera_position.overhead', 'overhead view'],
                [$lll . 'tt_content.dalleimage.prompt.camera_position.lowangle', 'low angle'],
                [$lll . 'tt_content.dalleimage.prompt.camera_position.aerial', 'aerial view'],
                [$lll . 'tt_content.dalleimage.prompt.camera_position.tilted', 'tilted frame'],
                [$lll . 'tt_content.dalleimage.prompt.camera_position.overtheshoulder', 'over the shoulder shot'],
            ],
        ],
    ],
    'tx_dalleimage_prompt_camera_lenses' => [
        'exclude' => true,
        'label' => $lll . 'tt_content.dalleimage.prompt.camera_lenses',
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.empty', ''],
                [$lll . 'tt_content.dalleimage.prompt.camera_lenses.fastshutterspeed', 'fast shutter speed'],
                [$lll . 'tt_content.dalleimage.prompt.camera_lenses.slowshutterspeed', 'slow shutter speed'],
                [$lll . 'tt_content.dalleimage.prompt.camera_lenses.bokeh', 'bokeh'],
                [$lll . 'tt_content.dalleimage.prompt.camera_lenses.tiltshift', 'tilt shift'],
                [$lll . 'tt_content.dalleimage.prompt.camera_lenses.motionblur', 'motion blur'],
                [$lll . 'tt_content.dalleimage.prompt.camera_lenses.telephotolens', 'telephoto lens'],
                [$lll . 'tt_content.dalleimage.prompt.camera_lenses.macrolens', 'macro lens'],
                [$lll . 'tt_content.dalleimage.prompt.camera_lenses.wideanglelens', 'wide angle lens'],
                [$lll . 'tt_content.dalleimage.prompt.camera_lenses.flasheyelens', 'flash eye lens'],
                [$lll . 'tt_content.dalleimage.prompt.camera_lenses.deepdepthoffield', 'deep depth of field'],
            ],              
        ],
    ],
    'tx_dalleimage_prompt_camera_shot' => [
        'exclude' => true,
        'label' => $lll . 'tt_content.dalleimage.prompt.camera_shot',
        'config' => [
          'type' => 'select',
          'renderType' => 'selectSingle',
          'items' => [
                [$lll . 'tt_content.dalleimage.prompt.empty', ''],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.closeup', 'close-up'],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.croppedcloseup', 'cropped close-up'],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.mediumshot', 'medium shot'],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.longshot', 'long shot'],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.overtheshouldershot', 'over-the-shoulder shot'],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.portrait', 'portrait'],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.fashionillustration', 'fashion illustration'],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.scientificillustration', 'scientific illustration'],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.silhouette', 'silhouette'],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.macroshot', 'macro shot'],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.goprocamera', 'GoPro camera'],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.droneshot', 'drone shot'],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.wideangleshot', 'wide-angle shot'],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.fisheye', 'fisheye'],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.tiltshiftphotography', 'tilt-shift photography'],
                [$lll . 'tt_content.dalleimage.prompt.camera_shot.cinematicmoviephotograph', 'cinematic movie photograph'],
            ],
        ],
    ],
    'tx_dalleimage_prompt_emotion' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.emotion',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectMultipleSideBySide',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.light', 'light'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.peaceful', 'peaceful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.calm', 'calm'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.serene', 'serene'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.soothing', 'soothing'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.relaxed', 'relaxed'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.placid', 'placid'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.comforting', 'comforting'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.cosy', 'cosy'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.tranquil', 'tranquil'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.quiet', 'quiet'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.pastel', 'pastel'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.delicate', 'delicate'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.graceful', 'graceful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.subtle', 'subtle'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.balmy', 'balmy'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.mild', 'mild'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.ethereal', 'ethereal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.elegant', 'elegant'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.tender', 'tender'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.soft', 'soft'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.bright', 'bright'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.vibrant', 'vibrant'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.dynamic', 'dynamic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.spirited', 'spirited'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.vivid', 'vivid'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.lively', 'lively'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.energetic', 'energetic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.colorful', 'colorful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.joyful', 'joyful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.romantic', 'romantic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.expressive', 'expressive'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.rich', 'rich'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.kaleidoscopic', 'kaleidoscopic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.psychedelic', 'psychedelic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.saturated', 'saturated'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.ecstatic', 'ecstatic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.brash', 'brash'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.exciting', 'exciting'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.passionate', 'passionate'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.hot', 'hot'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.muted', 'muted'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.bleak', 'bleak'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.funereal', 'funereal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.somber', 'somber'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.melancholic', 'melancholic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.mournful', 'mournful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.gloomy', 'gloomy'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.dismal', 'dismal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.sad', 'sad'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.pale', 'pale'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.washedout', 'washedout'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.desaturated', 'desaturated'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.grey', 'grey'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.subdued', 'subdued'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.dull', 'dull'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.dreary', 'dreary'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.depressing', 'depressing'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.weary', 'weary'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.tired', 'tired'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.haunting', 'haunting'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.dark', 'dark'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.gloomy', 'gloomy'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.dismal', 'dismal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.depressing', 'depressing'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.oppressive', 'oppressive'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.forbidding', 'forbidding'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.frightening', 'frightening'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.tense', 'tense'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.nervous', 'nervous'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.unsettling', 'unsettling'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.ominous', 'ominous'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.foreboding', 'foreboding'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.terrifying', 'terrifying'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.horrifying', 'horrifying'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.gruesome', 'gruesome'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.macabre', 'macabre'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.gory', 'gory'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.bloody', 'bloody'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.ghastly', 'ghastly'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.fearful', 'fearful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.scary', 'scary'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.evil', 'evil'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.diabolical', 'diabolical'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.wicked', 'wicked'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.sinister', 'sinister'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.menacing', 'menacing'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.satanic', 'satanic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.demonic', 'demonic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.destructive', 'destructive'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.violent', 'violent'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.cruel', 'cruel'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.barbaric', 'barbaric'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.malicious', 'malicious'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.hateful', 'hateful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.aggressive', 'aggressive'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.hostile', 'hostile'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.belligerent', 'belligerent'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.angry', 'angry'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.furious', 'furious'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.raging', 'raging'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.ferocious', 'ferocious'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.savagen', 'savage'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.brutal', 'brutal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.savage', 'savage'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.wild', 'wild'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.untamed', 'untamed'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.feral', 'feral'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.bloody', 'bloody'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.gory', 'gory'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.horror', 'horror'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.torturous', 'torturous'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.hellish', 'hellish'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.infernal', 'infernal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.dreadful', 'dreadful'],
            ],
            'size' => 10,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_composition' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.composition',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectMultipleSideBySide',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.curvaceous', 'curvaceous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.swirling', 'swirling'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.organic', 'organic'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.riotous', 'riotous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.turbulent', 'turbulent'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.flowing', 'flowing'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.amorphous', 'amorphous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.natural', 'natural'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.distorted', 'distorted'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.uneven', 'uneven'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.random', 'random'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.lush', 'lush'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.bold', 'bold'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.intuitive', 'intuitive'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.emotive', 'emotive'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.chaotic', 'chaotic'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.tumultuous', 'tumultuous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.earthy', 'earthy'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.churning', 'churning'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.monumental', 'monumental'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.imposing', 'imposing'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.rigorous', 'rigorous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.geometric', 'geometric'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.ordered', 'ordered'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.angular', 'angular'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.artificial', 'artificial'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.lines', 'lines'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.straight', 'straight'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.rhythmic', 'rhythmic'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.composed', 'composed'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.unified', 'unified'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.manmade', 'manmade'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.perspective', 'perspective'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.minimalist', 'minimalist'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.blocks', 'blocks'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.dignified', 'dignified'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.robust', 'robust'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.defined', 'defined'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.ornate','ornate'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.delicate', 'delicate'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.neat', 'neat'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.precise', 'precise'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.detailed', 'detailed'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.opulent', 'opulent'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.lavish', 'lavish'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.elegant', 'elegant'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.ornamented', 'ornamented'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.fine', 'fine'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.elaborate', 'elaborate'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.accurate', 'accurate'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.intricate', 'intricate'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.meticulous', 'meticulous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.decorative', 'decorative'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.realistic', 'realistic'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.unplanned', 'unplanned'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.daring', 'daring'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.brash', 'brash'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.random', 'random'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.casual', 'casual'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.sketched', 'sketched'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.playful', 'playful'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.spontaneous', 'spontaneous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.extemporaneous', 'extemporaneous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.offhand', 'offhand'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.improvisational', 'improvisational'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.experimental', 'experimental'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.loose', 'loose'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.jaunty', 'jaunty'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.light', 'light'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.expressive', 'expressive'],
            ], 
            'size' => 10,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
];

ExtensionManagementUtility::addTCAcolumns(
    'tt_content',
    $dalleImage
);

$dalleStylePalette = array(
    'tx_dalleimage_dalleStylePalette' => [
        'showitem' => 'tx_dalleimage_prompt_illustration, tx_dalleimage_prompt_style, tx_dalleimage_prompt_artworks, tx_dalleimage_prompt_artists', 
        'canNotCollapse' => 1
    ],
);

$GLOBALS['TCA']['tt_content']['palettes'] += $dalleStylePalette;

$dalleCameraPalette = array(
    'tx_dalleimage_dalleCameraPalette' => [
        'showitem' => 'tx_dalleimage_prompt_film_type, tx_dalleimage_prompt_camera_position, tx_dalleimage_prompt_camera_lenses, tx_dalleimage_prompt_camera_shot', 
        'canNotCollapse' => 1
    ],
);

$GLOBALS['TCA']['tt_content']['palettes'] += $dalleCameraPalette;

// Add the fields to palettes
ExtensionManagementUtility::addToAllTCAtypes(
	'tt_content',
	'--div--; Dalle Image,
    assets,
    tx_dalleimage_prompt_description, 
    tx_dalleimage_prompt_colors,
    tx_dalleimage_prompt_subject, 
    --palette--;'. $lll. 'tt_content.palette.illustration; tx_dalleimage_dalleStylePalette, 
    --palette--;'. $lll. 'tt_content.palette.camera; tx_dalleimage_dalleCameraPalette, 
    tx_dalleimage_prompt_lighting,
    tx_dalleimage_prompt_emotion, 
    tx_dalleimage_prompt_composition',
	'textmedia,image',
	'after:image_zoom'
);