<?php

use TYPO3\CMS\Core\Utility\ExtensionManagementUtility;

defined('TYPO3_MODE') or die();

$lll = 'LLL:EXT:sf_dalleimages/Resources/Private/Language/locallang_db.xlf:';

$dalleImage = [
    'tx_dalleimage_prompt_description' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.description',
        'exclude' => 1,
        'config' => [
            'type' => 'input',
            'renderType' => 'sendToDalleButton',
            'size' => 30,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_subject' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.subject',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'size' => 30,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_style' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.style',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
 
            ],
            'size' => 30,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_colors' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.colors',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                ['Static values', '--div--'],
                ['static -2', -2],
                ['static -1', -1],
                ['DB values', '--div--'],
            ],
            'size' => 30,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_emotion' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.emotion',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectMultipleSideBySide',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.light', 'light'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.peaceful', 'peaceful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.calm', 'calm'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.serene', 'serene'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.soothing', 'soothing'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.relaxed', 'relaxed'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.placid', 'placid'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.comforting', 'comforting'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.cosy', 'cosy'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.tranquil', 'tranquil'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.quiet', 'quiet'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.pastel', 'pastel'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.delicate', 'delicate'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.graceful', 'graceful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.subtle', 'subtle'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.balmy', 'balmy'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.mild', 'mild'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.ethereal', 'ethereal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.elegant', 'elegant'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.tender', 'tender'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.soft', 'soft'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.bright', 'bright'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.vibrant', 'vibrant'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.dynamic', 'dynamic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.spirited', 'spirited'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.vivid', 'vivid'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.lively', 'lively'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.energetic', 'energetic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.colorful', 'colorful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.joyful', 'joyful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.romantic', 'romantic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.expressive', 'expressive'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.rich', 'rich'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.kaleidoscopic', 'kaleidoscopic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.psychedelic', 'psychedelic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.saturated', 'saturated'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.ecstatic', 'ecstatic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.brash', 'brash'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.exciting', 'exciting'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.passionate', 'passionate'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.hot', 'hot'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.muted', 'muted'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.bleak', 'bleak'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.funereal', 'funereal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.somber', 'somber'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.melancholic', 'melancholic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.mournful', 'mournful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.gloomy', 'gloomy'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.dismal', 'dismal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.sad', 'sad'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.pale', 'pale'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.washedout', 'washedout'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.desaturated', 'desaturated'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.grey', 'grey'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.subdued', 'subdued'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.dull', 'dull'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.dreary', 'dreary'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.depressing', 'depressing'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.weary', 'weary'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.tired', 'tired'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.haunting', 'haunting'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.dark', 'dark'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.gloomy', 'gloomy'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.dismal', 'dismal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.depressing', 'depressing'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.oppressive', 'oppressive'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.forbidding', 'forbidding'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.frightening', 'frightening'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.tense', 'tense'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.nervous', 'nervous'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.unsettling', 'unsettling'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.ominous', 'ominous'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.foreboding', 'foreboding'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.terrifying', 'terrifying'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.horrifying', 'horrifying'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.gruesome', 'gruesome'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.macabre', 'macabre'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.gory', 'gory'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.bloody', 'bloody'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.ghastly', 'ghastly'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.fearful', 'fearful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.scary', 'scary'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.evil', 'evil'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.diabolical', 'diabolical'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.wicked', 'wicked'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.sinister', 'sinister'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.menacing', 'menacing'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.satanic', 'satanic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.demonic', 'demonic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.destructive', 'destructive'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.violent', 'violent'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.cruel', 'cruel'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.barbaric', 'barbaric'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.malicious', 'malicious'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.hateful', 'hateful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.aggressive', 'aggressive'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.hostile', 'hostile'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.belligerent', 'belligerent'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.angry', 'angry'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.furious', 'furious'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.raging', 'raging'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.ferocious', 'ferocious'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.savagen', 'savage'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.brutal', 'brutal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.savage', 'savage'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.wild', 'wild'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.untamed', 'untamed'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.feral', 'feral'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.bloody', 'bloody'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.gory', 'gory'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.horror', 'horror'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.torturous', 'torturous'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.hellish', 'hellish'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.infernal', 'infernal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.dreadful', 'dreadful'],
            ],
            'size' => 30,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_composition' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.composition',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                ['Static values', '--div--'],
                ['static -2', -2],
                ['static -1', -1],
                ['DB values', '--div--'],
            ],
            'size' => 30,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
];

ExtensionManagementUtility::addTCAcolumns(
    'tt_content',
    $dalleImage
);

// Add the field to the palette
ExtensionManagementUtility::addToAllTCAtypes(
	'tt_content',
	'tx_dalleimage_prompt_description, tx_dalleimage_prompt_subject, tx_dalleimage_prompt_style, tx_dalleimage_prompt_colors, tx_dalleimage_prompt_emotion, tx_dalleimage_prompt_composition',
	'textmedia,image',
	'after:assets'
);