<?php

use TYPO3\CMS\Core\Utility\ExtensionManagementUtility;

defined('TYPO3_MODE') or die();

$lll = 'LLL:EXT:sf_dalleimages/Resources/Private/Language/locallang_db.xlf:';

$dalleImage = [
    'tx_dalleimage_prompt_description' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.description',
        'exclude' => 1,
        'config' => [
            'type' => 'input',
            'renderType' => 'sendToDalleButton',
            'size' => 30,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_subject' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.subject',
        'exclude' => 1,
        'config' => [
            'type' => 'input',
            'size' => 10,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_illustration' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.illustration',
        'exclude' => 1,
        'config' => [
          'type' => 'select',
          'renderType' => 'selectSingle',
          'items' => [
            [$lll . 'tt_content.dalleimage.prompt.illustration.crayondrawing', 'crayondrawing'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.coloringbook', 'coloringbook'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.papercollage', 'papercollage'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.pencilsketch', 'pencilsketch'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.ballpensketch', 'ballpensketch'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.airbrush', 'airbrush'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.watercolor', 'watercolor'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.acryloncanvas', 'acryloncanvas'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.oilpainting', 'oilpainting'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.oilpastel', 'oilpastel'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.charcoaldrawing', 'charcoaldrawing'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.tattoodesign', 'tattoodesign'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.graffiti', 'graffiti'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.blueprint', 'blueprint'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.waxcrayon', 'waxcrayon'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.coloredink', 'coloredink'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.penandink', 'penandink'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.mythologicalmap', 'mythologicalmap'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.botanyillustration', 'botanyillustration'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.historicalarchive', 'historicalarchive'],
            [$lll . 'tt_content.dalleimage.prompt.illustration.medievalmanuscript', 'medievalmanuscript'],
        ],
      ],
    ],
    'tx_dalleimage_prompt_style' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.style',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.style', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.style.goth', 'goth'],
                [$lll . 'tt_content.dalleimage.prompt.style.vaporwave', 'Vaporwave'],
                [$lll . 'tt_content.dalleimage.prompt.style.postapocalyptic', 'postapokalyptisch'],
                [$lll . 'tt_content.dalleimage.prompt.style.cybernetic', 'kybernetisch'],
                [$lll . 'tt_content.dalleimage.prompt.style.steampunk', 'Steampunk'],
                [$lll . 'tt_content.dalleimage.prompt.style.memphis', 'Memphis'],
                [$lll . 'tt_content.dalleimage.prompt.style.dieselpunk', 'Dieselpunk'],
                [$lll . 'tt_content.dalleimage.prompt.style.afrofuturism', 'Afrofuturismus'],
                [$lll . 'tt_content.dalleimage.prompt.style.cyberpunk', 'Cyberpunk'],
                [$lll . 'tt_content.dalleimage.prompt.style.biopunk', 'Biopunk'],
                [$lll . 'tt_content.dalleimage.prompt.style.vintage', 'Vintage'],
                [$lll . 'tt_content.dalleimage.prompt.style.darkacademia', 'Dark Academia'],
                [$lll . 'tt_content.dalleimage.prompt.style.junglecore', 'Junglecore'],
                [$lll . 'tt_content.dalleimage.prompt.style.childrensdrawing', 'Kinderzeichnung'],
                [$lll . 'tt_content.dalleimage.prompt.style.popart', 'Pop Art'],
                [$lll . 'tt_content.dalleimage.prompt.style.princesscore', 'Princesscore'],
                [$lll . 'tt_content.dalleimage.prompt.style.psychedelica', 'Psychedelika'],
                [$lll . 'tt_content.dalleimage.prompt.style.rococo', 'Rokoko'],
                [$lll . 'tt_content.dalleimage.prompt.style.tanbikei', 'Tanbi Kei'],
                [$lll . 'tt_content.dalleimage.prompt.style.teslapunk', 'Teslapunk'],
                [$lll . 'tt_content.dalleimage.prompt.style.ukiyoe', 'Ukiyo-e'],
                [$lll . 'tt_content.dalleimage.prompt.style.wabisabi', 'Wabi-Sabi'],
                [$lll . 'tt_content.dalleimage.prompt.style.xrayimage', 'Röntgenbild'],
                [$lll . 'tt_content.dalleimage.prompt.style.infrared', 'Infrarot'],
                [$lll . 'tt_content.dalleimage.prompt.style.ultraviolet', 'Ultraviolett'],
                [$lll . 'tt_content.dalleimage.prompt.style.thermalphoto', 'Thermofoto'],
                [$lll . 'tt_content.dalleimage.prompt.style.1950ssuburbia', 'Vorstadt der 1950er'],
                [$lll . 'tt_content.dalleimage.prompt.style.2tone', '2 Tone'],
                [$lll . 'tt_content.dalleimage.prompt.style.2000sautumn', 'Herbst der 2000er'],
                [$lll . 'tt_content.dalleimage.prompt.style.2014eratumblr', 'Tumblr-Ära 2014'],
                [$lll . 'tt_content.dalleimage.prompt.style.2kanimecore', '2K Animecore'],
                [$lll . 'tt_content.dalleimage.prompt.style.70sdisco', '70er Disco'],
                [$lll . 'tt_content.dalleimage.prompt.style.uhd8k', 'UHD 8K'],
            ],
            'size' => 10,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_artworks' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.artworks',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.artworks.scoobydoo', 'scoobydoo'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.flintstones', 'flintstones'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.familyguy', 'familyguy'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.thesimpsons', 'thesimpsons'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.looneytunes', 'looneytunes'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.bojackhorseman', 'bojackhorseman'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.drseuss', 'drseuss'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.themuppetshow', 'themuppetshow'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.themoviematrix', 'themoviematrix'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.studioghibli', 'studioghibli'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.disney2d', 'disney2d'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.disney3d', 'disney3d'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.pixar', 'pixar'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.sincity', 'sincity'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.spidermanauniverse', 'spidermanauniverse'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.archer', 'archer'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.futurama', 'futurama'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.southpark', 'southpark'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.adventuretime', 'adventuretime'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.akira', 'akira'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.cowboybebop', 'cowboybebop'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.gorillaz', 'gorillaz'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.thelegendofkorra', 'thelegendofkorra'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.sailormoon', 'sailormoon'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.onepiece', 'onepiece'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.ghostintheshell', 'ghostintheshell'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.renandstimpy', 'renandstimpy'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.beavisandbutthead', 'beavisandbutthead'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.kingofthehill', 'kingofthehill'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.popeye', 'popeye'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.batmananimatedseries', 'batmananimatedseries'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.powerpuffgirls', 'powerpuffgirls'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.teenagemutantninjaturtles', 'teenagemutantninjaturtles'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.xmenanimatedseries', 'xmenanimatedseries'],
                [$lll . 'tt_content.dalleimage.prompt.artworks.myneighbor_totoro', 'myneighbor_totoro'],
            ],
            'size' => 10,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],

    'tx_dalleimage_prompt_artists' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.artists',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.artists.salvadordali', 'salvadordali'],
                [$lll . 'tt_content.dalleimage.prompt.artists.fridakahlo', 'fridakahlo'],
                [$lll . 'tt_content.dalleimage.prompt.artists.banksy', 'banksy'],
                [$lll . 'tt_content.dalleimage.prompt.artists.picasso', 'picasso'],
                [$lll . 'tt_content.dalleimage.prompt.artists.davinci', 'davinci'],
                [$lll . 'tt_content.dalleimage.prompt.artists.michelangelo', 'michelangelo'],
                [$lll . 'tt_content.dalleimage.prompt.artists.vangogh', 'vangogh'],
                [$lll . 'tt_content.dalleimage.prompt.artists.monet', 'monet'],
                [$lll . 'tt_content.dalleimage.prompt.artists.timburton', 'timburton'],
                [$lll . 'tt_content.dalleimage.prompt.artists.takashimurakami', 'takashimurakami'],
                [$lll . 'tt_content.dalleimage.prompt.artists.franciscodegoya', 'franciscodegoya'],
                [$lll . 'tt_content.dalleimage.prompt.artists.jeffkoons', 'jeffkoons'],
                [$lll . 'tt_content.dalleimage.prompt.artists.andywarhol', 'andywarhol'],
                [$lll . 'tt_content.dalleimage.prompt.artists.frankmiller', 'frankmiller'],
                [$lll . 'tt_content.dalleimage.prompt.artists.marjanesatrapi', 'marjanesatrapi'],
                [$lll . 'tt_content.dalleimage.prompt.artists.keithharing', 'keithharing'],
                [$lll . 'tt_content.dalleimage.prompt.artists.edwardhopper', 'edwardhopper'],
                [$lll . 'tt_content.dalleimage.prompt.artists.lisafrank', 'lisafrank'],
                [$lll . 'tt_content.dalleimage.prompt.artists.robertcrumb', 'robertcrumb'],
                [$lll . 'tt_content.dalleimage.prompt.artists.roylichenstein', 'roylichenstein'],
                [$lll . 'tt_content.dalleimage.prompt.artists.arthurrachkam', 'arthurrachkam'],
                [$lll . 'tt_content.dalleimage.prompt.artists.zahahadid', 'zahahadid'],
                [$lll . 'tt_content.dalleimage.prompt.artists.shraza', 'shraza'],
                [$lll . 'tt_content.dalleimage.prompt.artists.dorothealange', 'dorothealange'],
                [$lll . 'tt_content.dalleimage.prompt.artists.cindysherman', 'cindysherman'],
                [$lll . 'tt_content.dalleimage.prompt.artists.liuxiaodong', 'liuxiaodong'],
                [$lll . 'tt_content.dalleimage.prompt.artists.terryrichardson', 'terryrichardson'],
                [$lll . 'tt_content.dalleimage.prompt.artists.georgehurrell', 'georgehurrell'],
                [$lll . 'tt_content.dalleimage.prompt.artists.junjiito', 'junjiito'],
                [$lll . 'tt_content.dalleimage.prompt.artists.billwatterson', 'billwatterson'],
            ],
            'size' => 10,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_lighting' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.lighting',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.lighting.goldenhour', 'goldenhour'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.bluehour', 'bluehour'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.midday', 'midday'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.overcast', 'overcast'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.warm', 'warm'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.cold', 'cold'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.flashphotography', 'flashphotography'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.colorfullightning', 'colorfullightning'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.reallightsource', 'reallightsource'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.highkeylighting', 'highkeylighting'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.backlighting', 'backlighting'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.studiolighting', 'studiolighting'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.studioportrait', 'studioportrait'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.litfromabove', 'litfromabove'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.litfrombelow', 'litfrombelow'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.sidelighting', 'sidelighting'],
                [$lll . 'tt_content.dalleimage.prompt.lighting.softlighting', 'softlighting'],
            ],
            'size' => 10,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_film_type' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.filmtype',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.filmtype.cyanotype', 'cyanotype'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.blackandwhite', 'blackandwhite'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.redscale', 'redscale'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.infrared', 'infrared'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.bleachbypass', 'bleachbypass'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.instagramhipstamatic2015', 'instagramhipstamatic2015'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.contactsheet', 'contactsheet'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.coloursplash', 'coloursplash'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.solarised', 'solarised'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.anaglyph', 'anaglyph'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.polaroid600filmcolor', 'polaroid600filmcolor'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.kodakinfraredfilm', 'kodakinfraredfilm'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.kodakxrayfilm', 'kodakxrayfilm'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.kodakkodachromefilm', 'kodakkodachromefilm'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.kodachrome64', 'kodachrome64'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.kodakektar100', 'kodakektar100'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.fujisuperia200', 'fujisuperia200'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.fujipro400h', 'fujipro400h'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.fujichromevelvia100', 'fujichromevelvia100'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.ilfordhp5', 'ilfordhp5'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.ilforddelta3200', 'ilforddelta3200'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.konicaminoltapro200s', 'konicaminoltapro200s'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.anscochrome200', 'anscochrome200'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.ektachrome100', 'ektachrome100'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.lomochromepurple100400', 'lomochromepurple100400'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.lomochrometurquoise100400', 'lomochrometurquoise100400'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.lomographyxpro200', 'lomographyxpro200'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.heliochrome', 'heliochrome'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.polaroid600film', 'polaroid600film'],
                [$lll . 'tt_content.dalleimage.prompt.filmtype.revologstreak', 'revologstreak']
            ],
            'size' => 10,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_camera_position' => [
        'exclude' => true,
        'label' => $lll . 'tt_content.dalleimage.prompt.camera_position',
        'config' => [
            'type' => 'select',
            'renderType' => 'selectSingle',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.camera_position.overhead', 'overhead'],
                [$lll . 'tt_content.dalleimage.prompt.camera_position.lowangle', 'lowangle'],
                [$lll . 'tt_content.dalleimage.prompt.camera_position.aerial', 'aerial'],
                [$lll . 'tt_content.dalleimage.prompt.camera_position.tilted', 'tilted'],
                [$lll . 'tt_content.dalleimage.prompt.camera_position.overtheshoulder', 'overtheshoulder'],
            ],
        ],
    ],
    'tx_dalleimage_prompt_camera_lenses' => [
        'exclude' => true,
        'label' => $lll . 'tt_content.dalleimage.prompt.camera_lenses',
        'config' => [
          'type' => 'select',
          'renderType' => 'selectSingle',
          'items' => [
            [$lll . 'tt_content.dalleimage.prompt.camera_lenses.fastshutterspeed', 'fastshutterspeed'],
            [$lll . 'tt_content.dalleimage.prompt.camera_lenses.slowshutterspeed', 'slowshutterspeed'],
            [$lll . 'tt_content.dalleimage.prompt.camera_lenses.bokeh', 'bokeh'],
            [$lll . 'tt_content.dalleimage.prompt.camera_lenses.tiltshift', 'tiltshift'],
            [$lll . 'tt_content.dalleimage.prompt.camera_lenses.motionblur', 'motionblur'],
            [$lll . 'tt_content.dalleimage.prompt.camera_lenses.telephotolens', 'telephotolens'],
            [$lll . 'tt_content.dalleimage.prompt.camera_lenses.macrolens', 'macrolens'],
            [$lll . 'tt_content.dalleimage.prompt.camera_lenses.wideanglelens', 'wideanglelens'],
            [$lll . 'tt_content.dalleimage.prompt.camera_lenses.flasheyelens', 'flasheyelens'],
            [$lll . 'tt_content.dalleimage.prompt.camera_lenses.deepdepthoffield', 'deepdepthoffield'],
          ],
        ],
    ],
    'tx_dalleimage_prompt_camera_shot' => [
        'exclude' => true,
        'label' => $lll . 'tt_content.dalleimage.prompt.camera_shot',
        'config' => [
          'type' => 'select',
          'renderType' => 'selectSingle',
          'items' => [
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.closeup', 'closeup'],
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.croppedcloseup', 'croppedcloseup'],
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.mediumshot', 'mediumshot'],
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.longshot', 'longshot'],
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.overtheshouldershot', 'overtheshouldershot'],
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.portrait', 'portrait'],
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.fashionillustration', 'fashionillustration'],
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.scientificillustration', 'scientificillustration'],
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.silhouette', 'silhouette'],
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.macroshot', 'macroshot'],
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.goprocamera', 'goprocamera'],
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.droneshot', 'droneshot'],
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.wideangleshot', 'wideangleshot'],
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.fisheye', 'fisheye'],
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.tiltshiftphotography', 'tiltshiftphotography'],
            [$lll . 'tt_content.dalleimage.prompt.camera_shot.cinematicmoviephotograph', 'cinematicmoviephotograph'],
          ],
        ],
    ],
    'tx_dalleimage_prompt_colors' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.colors',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectMultipleSideBySide',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.colors.black', 'black'],
                [$lll . 'tt_content.dalleimage.prompt.colors.white', 'white'],
                [$lll . 'tt_content.dalleimage.prompt.colors.red', 'red'],
                [$lll . 'tt_content.dalleimage.prompt.colors.blue', 'blue'],
                [$lll . 'tt_content.dalleimage.prompt.colors.green', 'green'],
                [$lll . 'tt_content.dalleimage.prompt.colors.yellow', 'yellow'],
                [$lll . 'tt_content.dalleimage.prompt.colors.orange', 'orange'],
                [$lll . 'tt_content.dalleimage.prompt.colors.purple', 'purple'],
                [$lll . 'tt_content.dalleimage.prompt.colors.pink', 'pink'],
                [$lll . 'tt_content.dalleimage.prompt.colors.brown', 'brown'],
                [$lll . 'tt_content.dalleimage.prompt.colors.grey', 'grey'],
                [$lll . 'tt_content.dalleimage.prompt.colors.cyan', 'cyan'],
                [$lll . 'tt_content.dalleimage.prompt.colors.magenta', 'magenta'],
                [$lll . 'tt_content.dalleimage.prompt.colors.teal', 'teal'],
                [$lll . 'tt_content.dalleimage.prompt.colors.lime', 'lime'],
                [$lll . 'tt_content.dalleimage.prompt.colors.maroon', 'maroon'],
                [$lll . 'tt_content.dalleimage.prompt.colors.olive', 'olive'],
                [$lll . 'tt_content.dalleimage.prompt.colors.navy', 'navy'],
                [$lll . 'tt_content.dalleimage.prompt.colors.aqua', 'aqua'],
            ],
            'size' => 10,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_emotion' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.emotion',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectMultipleSideBySide',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.light', 'light'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.peaceful', 'peaceful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.calm', 'calm'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.serene', 'serene'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.soothing', 'soothing'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.relaxed', 'relaxed'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.placid', 'placid'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.comforting', 'comforting'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.cosy', 'cosy'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.tranquil', 'tranquil'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.quiet', 'quiet'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.pastel', 'pastel'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.delicate', 'delicate'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.graceful', 'graceful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.subtle', 'subtle'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.balmy', 'balmy'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.mild', 'mild'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.ethereal', 'ethereal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.elegant', 'elegant'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.tender', 'tender'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.low.soft', 'soft'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.bright', 'bright'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.vibrant', 'vibrant'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.dynamic', 'dynamic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.spirited', 'spirited'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.vivid', 'vivid'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.lively', 'lively'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.energetic', 'energetic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.colorful', 'colorful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.joyful', 'joyful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.romantic', 'romantic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.expressive', 'expressive'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.rich', 'rich'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.kaleidoscopic', 'kaleidoscopic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.psychedelic', 'psychedelic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.saturated', 'saturated'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.ecstatic', 'ecstatic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.brash', 'brash'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.exciting', 'exciting'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.passionate', 'passionate'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.positive.high.hot', 'hot'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.muted', 'muted'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.bleak', 'bleak'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.funereal', 'funereal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.somber', 'somber'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.melancholic', 'melancholic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.mournful', 'mournful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.gloomy', 'gloomy'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.dismal', 'dismal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.sad', 'sad'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.pale', 'pale'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.washedout', 'washedout'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.desaturated', 'desaturated'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.grey', 'grey'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.subdued', 'subdued'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.dull', 'dull'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.dreary', 'dreary'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.depressing', 'depressing'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.weary', 'weary'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.low.tired', 'tired'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.haunting', 'haunting'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.dark', 'dark'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.gloomy', 'gloomy'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.dismal', 'dismal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.depressing', 'depressing'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.oppressive', 'oppressive'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.forbidding', 'forbidding'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.frightening', 'frightening'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.tense', 'tense'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.nervous', 'nervous'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.unsettling', 'unsettling'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.ominous', 'ominous'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.foreboding', 'foreboding'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.terrifying', 'terrifying'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.horrifying', 'horrifying'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.gruesome', 'gruesome'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.macabre', 'macabre'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.gory', 'gory'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.bloody', 'bloody'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.ghastly', 'ghastly'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.fearful', 'fearful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.scary', 'scary'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.evil', 'evil'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.diabolical', 'diabolical'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.wicked', 'wicked'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.sinister', 'sinister'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.menacing', 'menacing'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.satanic', 'satanic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.demonic', 'demonic'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.destructive', 'destructive'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.violent', 'violent'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.cruel', 'cruel'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.barbaric', 'barbaric'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.malicious', 'malicious'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.hateful', 'hateful'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.aggressive', 'aggressive'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.hostile', 'hostile'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.belligerent', 'belligerent'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.angry', 'angry'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.furious', 'furious'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.raging', 'raging'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.ferocious', 'ferocious'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.savagen', 'savage'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.brutal', 'brutal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.savage', 'savage'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.wild', 'wild'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.untamed', 'untamed'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.feral', 'feral'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.bloody', 'bloody'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.gory', 'gory'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.horror', 'horror'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.torturous', 'torturous'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.hellish', 'hellish'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.infernal', 'infernal'],
                [$lll . 'tt_content.dalleimage.prompt.emotion.negative.high.dreadful', 'dreadful'],
            ],
            'size' => 10,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
    'tx_dalleimage_prompt_composition' => [
        'label' => $lll . 'tt_content.dalleimage.prompt.composition',
        'exclude' => 1,
        'config' => [
            'type' => 'select',
            'renderType' => 'selectMultipleSideBySide',
            'items' => [
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.curvaceous', 'bigandfree_curvaceous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.swirling', 'bigandfree_swirling'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.organic', 'bigandfree_organic'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.riotous', 'bigandfree_riotous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.turbulent', 'bigandfree_turbulent'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.flowing', 'bigandfree_flowing'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.amorphous', 'bigandfree_amorphous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.natural', 'bigandfree_natural'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.distorted', 'bigandfree_distorted'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.uneven', 'bigandfree_uneven'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.random', 'bigandfree_random'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.lush', 'bigandfree_lush'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.organic', 'bigandfree_organic'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.bold', 'bigandfree_bold'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.intuitive', 'bigandfree_intuitive'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.emotive', 'bigandfree_emotive'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.chaotic', 'bigandfree_chaotic'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.tumultuous', 'bigandfree_tumultuous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.earthy', 'bigandfree_earthy'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandfree.churning', 'bigandfree_churning'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.monumental', 'bigandstructured_monumental'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.imposing', 'bigandstructured_imposing'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.rigorous', 'bigandstructured_rigorous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.geometric', 'bigandstructured_geometric'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.ordered', 'bigandstructured_ordered'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.angular', 'bigandstructured_angular'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.artificial', 'bigandstructured_artificial'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.lines', 'bigandstructured_lines'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.straight', 'bigandstructured_straight'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.rhythmic', 'bigandstructured_rhythmic'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.composed', 'bigandstructured_composed'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.unified', 'bigandstructured_unified'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.manmade', 'bigandstructured_manmade'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.perspective', 'bigandstructured_perspective'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.minimalist', 'bigandstructured_minimalist'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.blocks', 'bigandstructured_blocks'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.dignified', 'bigandstructured_dignified'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.robust', 'bigandstructured_robust'],
                [$lll . 'tt_content.dalleimage.prompt.composition.bigandstructured.defined', 'bigandstructured_defined'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.ornate', 'smallandstructured_ornate'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.delicate', 'smallandstructured_delicate'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.neat', 'smallandstructured_neat'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.precise', 'smallandstructured_precise'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.detailed', 'smallandstructured_detailed'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.opulent', 'smallandstructured_opulent'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.lavish', 'smallandstructured_lavish'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.elegant', 'smallandstructured_elegant'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.ornamented', 'smallandstructured_ornamented'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.fine', 'smallandstructured_fine'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.elaborate', 'smallandstructured_elaborate'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.accurate', 'smallandstructured_accurate'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.intricate', 'smallandstructured_intricate'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.meticulous', 'smallandstructured_meticulous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.decorative', 'smallandstructured_decorative'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandstructured.realistic', 'smallandstructured_realistic'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree', '--div--'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.unplanned', 'smallandfree_unplanned'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.daring', 'smallandfree_daring'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.brash', 'smallandfree_brash'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.random', 'smallandfree_random'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.casual', 'smallandfree_casual'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.sketched', 'smallandfree_sketched'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.playful', 'smallandfree_playful'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.spontaneous', 'smallandfree_spontaneous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.extemporaneous', 'smallandfree_extemporaneous'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.offhand', 'smallandfree_offhand'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.improvisational', 'smallandfree_improvisational'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.experimental', 'smallandfree_experimental'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.loose', 'smallandfree_loose'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.jaunty', 'smallandfree_jaunty'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.light', 'smallandfree_light'],
                [$lll . 'tt_content.dalleimage.prompt.composition.smallandfree.expressive', 'smallandfree_expressive'],
            ],
            'size' => 10,
            'max' => 255,
            'eval' => 'trim',
        ],
    ],
];

ExtensionManagementUtility::addTCAcolumns(
    'tt_content',
    $dalleImage
);

// Add the field to the palette
ExtensionManagementUtility::addToAllTCAtypes(
	'tt_content',
	'tx_dalleimage_prompt_description, tx_dalleimage_prompt_subject, tx_dalleimage_prompt_style, tx_dalleimage_prompt_artworks, tx_dalleimage_prompt_artists, tx_dalleimage_prompt_lighting, tx_dalleimage_prompt_film_type, tx_dalleimage_prompt_colors, tx_dalleimage_prompt_emotion, tx_dalleimage_prompt_composition',
	'textmedia,image',
	'after:assets'
);