services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Stackfactory\SfDalleimages\:
    resource: '../Classes/*'

  Stackfactory\SfDalleimages\Utility\DalleUtility:
    public: true
    