services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Stackfactory\SfDalleimages\:
    resource: '../Classes/*'

  Stackfactory\SfDalleimages\Services\ImageService:
    public: true
    
  Stackfactory\SfDalleimages\Services\UriService:
    public: true
    
  Stackfactory\SfDalleimages\Controller\AjaxController:
    public: true

  Stackfactory\SfDalleimages\Tca\PreviewImages:
    public: true
    arguments:
      $nodeFactory: '@TYPO3\CMS\Backend\Form\NodeFactory'
      $data: []
      $eventDispatcher: '@Psr\EventDispatcher\EventDispatcherInterface'
    