services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Stackfactory\SfDalleimages\:
    resource: '../Classes/*'

  Stackfactory\SfDalleimages\Services\ImageService:
    public: true
    
  Stackfactory\SfDalleimages\Controller\AjaxController:
    public: true
    